// <auto-generated />
using BlazorCheatSheet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCheatSheet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102235843_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorCheatSheet.Shared.Domain.YogaClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YogaClassTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YogaClassTypeId");

                    b.ToTable("YogaClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A gentle Hatha yoga class to start your day.",
                            Name = "Morning Hatha Flow",
                            YogaClassTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "An energetic Vinyasa class to build strength and flexibility.",
                            Name = "Power Vinyasa",
                            YogaClassTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "A traditional Ashtanga yoga class following the primary series.",
                            Name = "Ashtanga Primary Series",
                            YogaClassTypeId = 3
                        });
                });

            modelBuilder.Entity("BlazorCheatSheet.Shared.Domain.YogaClassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YogaClassTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hatha"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vinyasa"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ashtanga"
                        });
                });

            modelBuilder.Entity("BlazorCheatSheet.Shared.Domain.YogaClass", b =>
                {
                    b.HasOne("BlazorCheatSheet.Shared.Domain.YogaClassType", "YogaClassType")
                        .WithMany()
                        .HasForeignKey("YogaClassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YogaClassType");
                });
#pragma warning restore 612, 618
        }
    }
}
